// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `resolve_default_index_path`

Future<String> ping() => RustLib.instance.api.crateApiPing();

Future<void> engineOpen({required String indexPathStr}) =>
    RustLib.instance.api.crateApiEngineOpen(indexPathStr: indexPathStr);

Future<void> engineClose() => RustLib.instance.api.crateApiEngineClose();

Future<BigInt> search({
  required String query,
  required int sortCol,
  required bool ascending,
}) => RustLib.instance.api.crateApiSearch(
  query: query,
  sortCol: sortCol,
  ascending: ascending,
);

Future<SearchStatusFfi> searchStatus({required BigInt generation}) =>
    RustLib.instance.api.crateApiSearchStatus(generation: generation);

Future<RowBatchFfi> rows({
  required BigInt generation,
  required int offset,
  required int count,
}) => RustLib.instance.api.crateApiRows(
  generation: generation,
  offset: offset,
  count: count,
);

Future<String> fullPath({required BigInt generation, required int row}) =>
    RustLib.instance.api.crateApiFullPath(generation: generation, row: row);

Future<void> revealInExplorer({required BigInt generation, required int row}) =>
    RustLib.instance.api.crateApiRevealInExplorer(
      generation: generation,
      row: row,
    );

Future<LicenseInfoFfi> getLicenseStatus() =>
    RustLib.instance.api.crateApiGetLicenseStatus();

Future<LicenseInfoFfi> activateProductKey({required String key}) =>
    RustLib.instance.api.crateApiActivateProductKey(key: key);

class LicenseInfoFfi {
  final bool isValid;
  final bool isTrial;
  final int trialDaysLeft;
  final String? licenseKey;
  final String hwid;
  final int productId;

  const LicenseInfoFfi({
    required this.isValid,
    required this.isTrial,
    required this.trialDaysLeft,
    this.licenseKey,
    required this.hwid,
    required this.productId,
  });

  @override
  int get hashCode =>
      isValid.hashCode ^
      isTrial.hashCode ^
      trialDaysLeft.hashCode ^
      licenseKey.hashCode ^
      hwid.hashCode ^
      productId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LicenseInfoFfi &&
          runtimeType == other.runtimeType &&
          isValid == other.isValid &&
          isTrial == other.isTrial &&
          trialDaysLeft == other.trialDaysLeft &&
          licenseKey == other.licenseKey &&
          hwid == other.hwid &&
          productId == other.productId;
}

class RowBatchFfi {
  final BigInt generation;
  final int offset;
  final int count;
  final List<String> names;
  final List<String> paths;
  final List<String> extensions;
  final Uint64List sizes;
  final Uint32List mtimes;
  final Uint8List flags;

  const RowBatchFfi({
    required this.generation,
    required this.offset,
    required this.count,
    required this.names,
    required this.paths,
    required this.extensions,
    required this.sizes,
    required this.mtimes,
    required this.flags,
  });

  @override
  int get hashCode =>
      generation.hashCode ^
      offset.hashCode ^
      count.hashCode ^
      names.hashCode ^
      paths.hashCode ^
      extensions.hashCode ^
      sizes.hashCode ^
      mtimes.hashCode ^
      flags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RowBatchFfi &&
          runtimeType == other.runtimeType &&
          generation == other.generation &&
          offset == other.offset &&
          count == other.count &&
          names == other.names &&
          paths == other.paths &&
          extensions == other.extensions &&
          sizes == other.sizes &&
          mtimes == other.mtimes &&
          flags == other.flags;
}

class SearchStatusFfi {
  final int readyCount;
  final int totalCount;
  final bool isComplete;
  final BigInt generation;
  final BigInt elapsedMs;

  const SearchStatusFfi({
    required this.readyCount,
    required this.totalCount,
    required this.isComplete,
    required this.generation,
    required this.elapsedMs,
  });

  @override
  int get hashCode =>
      readyCount.hashCode ^
      totalCount.hashCode ^
      isComplete.hashCode ^
      generation.hashCode ^
      elapsedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchStatusFfi &&
          runtimeType == other.runtimeType &&
          readyCount == other.readyCount &&
          totalCount == other.totalCount &&
          isComplete == other.isComplete &&
          generation == other.generation &&
          elapsedMs == other.elapsedMs;
}
