// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CrumbFfi dco_decode_crumb_ffi(dynamic raw);

  @protected
  EngineStatusFfi dco_decode_engine_status_ffi(dynamic raw);

  @protected
  FileOpFfi dco_decode_file_op_ffi(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<bool> dco_decode_list_bool(dynamic raw);

  @protected
  List<CrumbFfi> dco_decode_list_crumb_ffi(dynamic raw);

  @protected
  List<FileOpFfi> dco_decode_list_file_op_ffi(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  RowBatchFfi dco_decode_row_batch_ffi(dynamic raw);

  @protected
  SearchStatusFfi dco_decode_search_status_ffi(dynamic raw);

  @protected
  ServiceStatusFfi dco_decode_service_status_ffi(dynamic raw);

  @protected
  TuningFfi dco_decode_tuning_ffi(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CrumbFfi sse_decode_crumb_ffi(SseDeserializer deserializer);

  @protected
  EngineStatusFfi sse_decode_engine_status_ffi(SseDeserializer deserializer);

  @protected
  FileOpFfi sse_decode_file_op_ffi(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<bool> sse_decode_list_bool(SseDeserializer deserializer);

  @protected
  List<CrumbFfi> sse_decode_list_crumb_ffi(SseDeserializer deserializer);

  @protected
  List<FileOpFfi> sse_decode_list_file_op_ffi(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  RowBatchFfi sse_decode_row_batch_ffi(SseDeserializer deserializer);

  @protected
  SearchStatusFfi sse_decode_search_status_ffi(SseDeserializer deserializer);

  @protected
  ServiceStatusFfi sse_decode_service_status_ffi(SseDeserializer deserializer);

  @protected
  TuningFfi sse_decode_tuning_ffi(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_crumb_ffi(CrumbFfi self, SseSerializer serializer);

  @protected
  void sse_encode_engine_status_ffi(
    EngineStatusFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_op_ffi(FileOpFfi self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bool(List<bool> self, SseSerializer serializer);

  @protected
  void sse_encode_list_crumb_ffi(List<CrumbFfi> self, SseSerializer serializer);

  @protected
  void sse_encode_list_file_op_ffi(
    List<FileOpFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_row_batch_ffi(RowBatchFfi self, SseSerializer serializer);

  @protected
  void sse_encode_search_status_ffi(
    SearchStatusFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_service_status_ffi(
    ServiceStatusFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tuning_ffi(TuningFfi self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
