// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 433713044;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'bdj_search_ffi',
        ioDirectory: '../engine/bdj_search_ffi/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiEngineClose();

  Future<void> crateApiEngineOpen({required String indexDir});

  Future<String> crateApiFullPath({
    required BigInt generation,
    required int row,
  });

  Future<String> crateApiPing();

  Future<void> crateApiRevealInExplorer({
    required BigInt generation,
    required int row,
  });

  Future<RowBatchFfi> crateApiRows({
    required BigInt generation,
    required int offset,
    required int count,
  });

  Future<BigInt> crateApiSearch({
    required String query,
    required int sortCol,
    required bool ascending,
  });

  Future<SearchStatusFfi> crateApiSearchStatus({required BigInt generation});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiEngineClose() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineCloseConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineCloseConstMeta =>
      const TaskConstMeta(debugName: "engine_close", argNames: []);

  @override
  Future<void> crateApiEngineOpen({required String indexDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(indexDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiEngineOpenConstMeta,
        argValues: [indexDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineOpenConstMeta =>
      const TaskConstMeta(debugName: "engine_open", argNames: ["indexDir"]);

  @override
  Future<String> crateApiFullPath({
    required BigInt generation,
    required int row,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(generation, serializer);
          sse_encode_u_32(row, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFullPathConstMeta,
        argValues: [generation, row],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFullPathConstMeta => const TaskConstMeta(
    debugName: "full_path",
    argNames: ["generation", "row"],
  );

  @override
  Future<String> crateApiPing() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPingConstMeta =>
      const TaskConstMeta(debugName: "ping", argNames: []);

  @override
  Future<void> crateApiRevealInExplorer({
    required BigInt generation,
    required int row,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(generation, serializer);
          sse_encode_u_32(row, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRevealInExplorerConstMeta,
        argValues: [generation, row],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRevealInExplorerConstMeta => const TaskConstMeta(
    debugName: "reveal_in_explorer",
    argNames: ["generation", "row"],
  );

  @override
  Future<RowBatchFfi> crateApiRows({
    required BigInt generation,
    required int offset,
    required int count,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(generation, serializer);
          sse_encode_u_32(offset, serializer);
          sse_encode_u_32(count, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_row_batch_ffi,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRowsConstMeta,
        argValues: [generation, offset, count],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRowsConstMeta => const TaskConstMeta(
    debugName: "rows",
    argNames: ["generation", "offset", "count"],
  );

  @override
  Future<BigInt> crateApiSearch({
    required String query,
    required int sortCol,
    required bool ascending,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_u_8(sortCol, serializer);
          sse_encode_bool(ascending, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSearchConstMeta,
        argValues: [query, sortCol, ascending],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchConstMeta => const TaskConstMeta(
    debugName: "search",
    argNames: ["query", "sortCol", "ascending"],
  );

  @override
  Future<SearchStatusFfi> crateApiSearchStatus({required BigInt generation}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(generation, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_search_status_ffi,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSearchStatusConstMeta,
        argValues: [generation],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchStatusConstMeta =>
      const TaskConstMeta(debugName: "search_status", argNames: ["generation"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeUint64List(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  RowBatchFfi dco_decode_row_batch_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return RowBatchFfi(
      generation: dco_decode_u_64(arr[0]),
      offset: dco_decode_u_32(arr[1]),
      count: dco_decode_u_32(arr[2]),
      names: dco_decode_list_String(arr[3]),
      paths: dco_decode_list_String(arr[4]),
      extensions: dco_decode_list_String(arr[5]),
      sizes: dco_decode_list_prim_u_64_strict(arr[6]),
      mtimes: dco_decode_list_prim_u_32_strict(arr[7]),
      flags: dco_decode_list_prim_u_8_strict(arr[8]),
    );
  }

  @protected
  SearchStatusFfi dco_decode_search_status_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SearchStatusFfi(
      readyCount: dco_decode_u_32(arr[0]),
      totalCount: dco_decode_u_32(arr[1]),
      isComplete: dco_decode_bool(arr[2]),
      generation: dco_decode_u_64(arr[3]),
      elapsedMs: dco_decode_u_64(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  RowBatchFfi sse_decode_row_batch_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_generation = sse_decode_u_64(deserializer);
    var var_offset = sse_decode_u_32(deserializer);
    var var_count = sse_decode_u_32(deserializer);
    var var_names = sse_decode_list_String(deserializer);
    var var_paths = sse_decode_list_String(deserializer);
    var var_extensions = sse_decode_list_String(deserializer);
    var var_sizes = sse_decode_list_prim_u_64_strict(deserializer);
    var var_mtimes = sse_decode_list_prim_u_32_strict(deserializer);
    var var_flags = sse_decode_list_prim_u_8_strict(deserializer);
    return RowBatchFfi(
      generation: var_generation,
      offset: var_offset,
      count: var_count,
      names: var_names,
      paths: var_paths,
      extensions: var_extensions,
      sizes: var_sizes,
      mtimes: var_mtimes,
      flags: var_flags,
    );
  }

  @protected
  SearchStatusFfi sse_decode_search_status_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_readyCount = sse_decode_u_32(deserializer);
    var var_totalCount = sse_decode_u_32(deserializer);
    var var_isComplete = sse_decode_bool(deserializer);
    var var_generation = sse_decode_u_64(deserializer);
    var var_elapsedMs = sse_decode_u_64(deserializer);
    return SearchStatusFfi(
      readyCount: var_readyCount,
      totalCount: var_totalCount,
      isComplete: var_isComplete,
      generation: var_generation,
      elapsedMs: var_elapsedMs,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_row_batch_ffi(RowBatchFfi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.generation, serializer);
    sse_encode_u_32(self.offset, serializer);
    sse_encode_u_32(self.count, serializer);
    sse_encode_list_String(self.names, serializer);
    sse_encode_list_String(self.paths, serializer);
    sse_encode_list_String(self.extensions, serializer);
    sse_encode_list_prim_u_64_strict(self.sizes, serializer);
    sse_encode_list_prim_u_32_strict(self.mtimes, serializer);
    sse_encode_list_prim_u_8_strict(self.flags, serializer);
  }

  @protected
  void sse_encode_search_status_ffi(
    SearchStatusFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.readyCount, serializer);
    sse_encode_u_32(self.totalCount, serializer);
    sse_encode_bool(self.isComplete, serializer);
    sse_encode_u_64(self.generation, serializer);
    sse_encode_u_64(self.elapsedMs, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
